version: '3'

services:
  db:
     container_name: pg_database
     image: postgres:14-alpine
     restart: always
     environment:
       POSTGRES_USER: root
       POSTGRES_PASSWORD: root1234
       POSTGRES_DB: mydb
     volumes:
       - ./postgres_data:/var/lib/postgresql/data/
     ports:
       - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@dps.bt
      PGADMIN_DEFAULT_PASSWORD: root1234
    ports:
      - "5050:80"