  - name: Add Docker GPG apt Key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: true
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    become: true
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Install Docker Module for Python
    pip:
      name: ['docker', 'docker-compose']
  
  - name: Starting Docker service
    become: true
    service:
      name: docker
      state: started
      enabled: true

  - name: Adding user to Docker group
    become: true
    user:
      name: "{{ user }}"
      groups: docker
      append: true

  - name: Installing and Upgrading Docker-Compose
    become: true
    get_url:
      url : "https://github.com/docker/compose/releases/download/{{ dockerComposeVersion }}/docker-compose-Linux-x86_64"
      dest: /usr/local/bin/docker-compose
      mode: 'a+x'
      force: yes
    when: >
      docker_compose_current_version is not defined
      or docker_compose_current_version is version(dockerComposeVersion, '<')